import { makeStyles } from '@mui/styles';

export default makeStyles(() => ({
    outerContainer: {
        position: 'absolute',
        left: '50%',
        top: '50%',
        transform: 'translate(-50%, -50%)',
        zIndex: '10',
        minWidth: '80vw',
        maxWidth: '80vw',
        minHeight: '60vh',
        maxHeight: '95vh',
        borderRadius: '20px',
        backgroundColor: 'seagreen',
        filter: 'drop-shadow(5px 5px 5px #333)',
        paddingTop: '0.5vh',
        padding: '2vh',
    },
    itemList: {
        display: 'inline-block',
        maxWidth: '50%',
    },
    itemIcon: {
        width: '5vw',
        filter: 'drop-shadow(3px 3px 2px #333)',
        border: '3px solid black',
        borderRadius: '25%',
        backgroundColor: 'aliceblue',
        marginLeft: '5px',
        padding: '5px',
    },
    itemTypeIcon: {
        filter: 'drop-shadow(1px 1px 2px #333)',
        margin: '0.5vh',
        height: '6vh',
        width: '6vh',
        opacity: '0.7',
    },
    slotIcon: {
        border: '3px solid black',
        height: '6vh',
        width: '6vh',
        borderRadius: '25%',
        background: 'aliceblue',
        padding: '0.5vh',
        marginLeft: '1vh',
        filter: 'drop-shadow(1px 1px 1px #333)',
    },
    itemSlot: {
        display: 'inline-block',
        position: 'absolute',
        right: '3vh',
        border: '3px solid black',
        borderRadius: '5px',
        margin: '0.5vh !important',
        marginRight: '5vh', 
        padding: '1vh',
        width: '50%',
        backgroundColor: 'lightgreen',
        filter: 'drop-shadow(2px 2px 2px #333)',
        height: '40vh',
    },
    title: {
        color: 'aliceblue',
        fontFamily: 'Verdana',
        fontSize: '4vh',
        textShadow: '1px 1px 2px #333',
        display: 'inline-block',
    },
    subtitle: {
        color: 'aliceblue',
        fontFamily: 'Verdana',
        fontSize: '2vh',
        marginLeft: '2vh',
        textShadow: '1px 1px 2px #333',
        display: 'inline-block',
    },
    itemTitle: {
        fontFamily: 'Verdana',
        fontWeight: 'bold',
        fontSize: '3vh',
        margin: '1vh',
    },
    itemDescription: {
        fontFamily: 'Verdana',
        fontSize: '2vh',
        margin: '1vh',
    },
    itemFlavor: {
        fontFamily: 'Verdana',
        fontSize: '2vh',
        margin: '1vh',
    },
    closeButton: {
        display: 'inline-block',
        position: 'absolute',
        fontFamily: 'Verdana',
        color: 'black',
        fontWeight: 'bold',
        width: '100px',
        fontSize: '2vh',
        margin: '1vh',
        backgroundColor: 'aliceblue',
        border: 'solid 3px black',
        filter: 'drop-shadow(2px 2px 2px #333)',
        borderRadius: '1vh',
        bottom: '2vh',
    }
}));