import { makeStyles } from '@mui/styles';

export default makeStyles(() => ({
    tile: {
        background: 'lightgreen',
        fontSize: '5vh',
        justifyContent: 'center',
        color: 'black',
        height: '5.8vh',
        width: '5.8vh',
        border: '0.1vh solid mediumseagreen',
        pointerEvents: 'all',
    },
    icon: {
        height: '5.8vh',
        width: '5.8vh',
        borderStyle: 'none',
        pointerEvents: 'none',
    },
    outerContainer: {
        margin: '0.4vh',
        width: '5vh',
        height: '5vh',
        overflow: 'auto',
        position: 'absolute',
        marginTop: '10px',
        marginBottom: '10px',
        pointerEvents: 'none',
    },
    healthBarContainer: {
        position: 'relative',
        width: '4.5aw vh',
        height: '1vh',
        backgroundColor: '#222222',
        borderRadius: '0.5vh',
        zIndex: '1',
        bottom: '0.2vm',
        textShadow: '1px 1px 1px #222',
        border: '0.1vh solid black',
        pointerEvents: 'none',
    },
    healthBar: {
        height: '1vh',
        borderRadius: '0.5vh',
        // position: 'relative',
        zIndex: '2',
        pointerEvents: 'none',
        backgroundColor: 'mediumseagreen',
    },
    barInfoText: {
        position: 'absolute',
        color: 'aliceblue',
        zIndex: '3',
        pointerEvents: 'none',
        fontFamily: 'Verdana',
        fontSize: '1.2vh',
        width: '100%',
        textAlign: 'center',
        fontWeight: 'bold',
        textShadow: '0px 0px 3px #111',
    },
}));