import { makeStyles } from '@mui/styles';

export default makeStyles(() => ({
    outerContainer: {
        position: 'absolute',
        left: '50%',
        top: '50%',
        transform: 'translate(-50%, -50%)',
        zIndex: '10',
        minWidth: '45%',
        padding: '20px',
        maxHeight: '95vh',
        borderRadius: '20px',
        background: 'seagreen',
        filter: 'drop-shadow(5px 5px 5px #333)',
        paddingTop: '0.5vh',
        paddingBottom: '1vh',
    },
    title: {
        color: 'aliceblue',
        width: '100%',
        textAlign: 'center',
        fontFamily: 'Verdana',
        fontSize: '2rem',
        textShadow: '1px 1px 2px #333',
        margin: '10px',
    },
    subtitle: {
        color: 'aliceblue',
        fontFamily: 'Verdana',
        width: '100%',
        // textAlign: 'center',
        fontSize: '1.5rem',
        textShadow: '1px 1px 2px #333',
        display: 'inline-block',
    },
    button: {
        display: 'inline-block',
        fontFamily: 'Verdana',
        color: 'black',
        fontWeight: 'bold',
        width: '50%',
        fontSize: '2vh',
        // margin: '0 25%',
        background: 'mediumseagreen',
        border: 'solid 3px black',
        filter: 'drop-shadow(2px 2px 2px #333)',
        borderRadius: '1vh',
    },
    handButton: {
        display: 'inline-block',
        fontFamily: 'Verdana',
        color: '#444',
        fontWeight: 'bold',
        width: '25%',
        fontSize: '2vh',
        marginRight: '2%',
        background: 'grey',
        border: 'solid 3px black',
        filter: 'drop-shadow(2px 2px 2px #333)',
        borderRadius: '1vh',
    },
    handButtonSelected: {
        display: 'inline-block',
        fontFamily: 'Verdana',
        color: 'black',
        fontWeight: 'bold',
        width: '25%',
        fontSize: '2vh',
        marginRight: '2%',
        background: 'mediumseagreen',
        border: 'solid 3px black',
        filter: 'drop-shadow(2px 2px 2px #333)',
        borderRadius: '1vh',
    },
    usernameTextbox: {
        fontFamily: 'Verdana',
        fontSize: '1rem',
        padding: '5px',
        width: '60%',
        height: '40px',
    },
}));