import { makeStyles } from '@mui/styles';

export default makeStyles(() => ({
    outerContainer: {
        position: 'absolute',
        left: '50%',
        top: '50%',
        transform: 'translate(-50%, -50%)',
        zIndex: '10',
        minWidth: '80vw',
        maxWidth: '80vw',
        maxHeight: '95vh',
        borderRadius: '20px',
        background: 'seagreen',
        filter: 'drop-shadow(5px 5px 5px #333)',
        paddingTop: '0.5vh',
        paddingBottom: '1vh',
    },
    title: {
        color: 'aliceblue',
        fontFamily: 'Verdana',
        fontSize: '3vh',
        textShadow: '1px 1px 2px #333',
        margin: '10px',
    },
    subtitle: {
        color: 'aliceblue',
        fontFamily: 'Verdana',
        fontSize: '1.5vh',
        textShadow: '1px 1px 2px #333',
        display: 'inline-block',
    },
    label: {
        color: 'aliceblue',
        fontFamily: 'Verdana',
    },
    button: {
        display: 'inline-block',
        fontFamily: 'Verdana',
        color: 'black',
        fontWeight: 'bold',
        width: '100px',
        fontSize: '2vh',
        margin: '1vh',
        background: 'aliceblue',
        border: 'solid 3px black',
        filter: 'drop-shadow(2px 2px 2px #333)',
        borderRadius: '1vh',
    },
    handButton: {
        display: 'inline-block',
        fontFamily: 'Verdana',
        color: 'black',
        fontWeight: 'bold',
        width: '100px',
        fontSize: '2vh',
        marginRight: '10px',
        background: 'aliceblue',
        border: 'solid 3px black',
        filter: 'drop-shadow(2px 2px 2px #333)',
        borderRadius: '1vh',
    },
    handButtonSelected: {
        display: 'inline-block',
        fontFamily: 'Verdana',
        color: 'black',
        fontWeight: 'bold',
        width: '100px',
        fontSize: '2vh',
        marginRight: '10px',
        background: 'lightseagreen',
        border: 'solid 3px black',
        filter: 'drop-shadow(2px 2px 2px #333)',
        borderRadius: '1vh',
    },
}));